version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER:-hello_django}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-hello_django}
      - POSTGRES_DB=${SQL_DATABASE:-hello_django_dev}

  django:
    build: ./app
    env_file:
      - ./app/.env.dev
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
