# Generated by Django 5.1.3 on 2024-11-16 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='vm',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vm',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vm',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vm',
            name='cpus',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vm',
            name='name',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vm',
            name='ram',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='SshKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('public_key', models.TextField()),
                ('vms', models.ManyToManyField(related_name='ssh_keys', to='cloud.vm')),
            ],
        ),
    ]
